name: roadrealm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.7
  firebase_auth: ^4.17.7
  firebase_core: ^2.26.0
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.3
  google_maps_flutter_web: ^0.5.4+3
   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
  - assets/Logo/Road_Realm_Logo.png
  - assets/fondo.png
  - assets/fondo_login.png

  uses-material-design: true
