name: roadrealm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.3
  geolocator: ^7.7.0
  google_maps_webservice: ^0.0.20-nullsafety.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:

    - assets/ImagenesFondo/FondoPaginaInicial.jpg
    - assets/ImagenesFondo/FondoPaginaEventos.jpg
    - assets/Logo/Road_Realm_Logo.png
    - assets/Eventos/Evento1.jpg
    - assets/Eventos/Evento2.jpg
    - assets/Eventos/Evento3.jpg
    - assets/flechaDerecha.png
    - assets/flechaIzquierda.png
    - assets/Rutas/Ruta1.png
    - assets/Rutas/Ruta2.png
    - assets\ModificarCuentarImag\avatarDefault.jpg

  uses-material-design: true
